package com.bookstore.entity;
// Generated Apr 16, 2019 10:47:01 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@NamedQueries(value = { @NamedQuery(name = "Users.findAll", query = "SELECT u from Users u ORDER BY u.fullName"),
		@NamedQuery(name = "Users.countAll", query = "SELECT Count(*) FROM Users"),
		@NamedQuery(name = "Users.findByEmail", query = "SELECT u FROM Users u where u.email = :email"),
		@NamedQuery(name = "Users.checkLogin", query = "SELECT u FROM Users u where u.email = :email and password = :pass")})
@Table(name = "users", catalog = "bookstoredb")
public class Users implements java.io.Serializable {

	public Users() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Users(String email, String password, String fullName) {
		super();
		this.email = email;
		this.password = password;
		this.fullName = fullName;
	}
	
	public Users(Integer userId, String email, String password, String fullName) {
		super();
		this.userId = userId;
		this.email = email;
		this.password = password;
		this.fullName = fullName;
	}

	private int userId;
	private String email;
	private String password;
	private String fullName;

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 16)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "full_name", nullable = false, length = 30)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

}
